# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FacebookDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FacebookDemo

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'SDWebImage', '~>3.8'

end
