# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'JobInterview' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JobInterview
  pod 'Alamofire', '~> 4.0'
  pod 'CCBottomRefreshControl'
  pod 'SDWebImage', '~>3.8'
  pod 'Toast', '~> 3.1.0'

end
